using System;
using System.Collections.Generic;
using UnityEngine;

// Offline country identity/strength source, generated by CountryCatalogBuilder.
[CreateAssetMenu(fileName = "CountryCatalog", menuName = "Water Polo/Country Catalog")]
public sealed class CountryCatalog : ScriptableObject
{
    [Serializable]
    public sealed class Entry
    {
        public string country;
        [Range(0, 100)] public int winRate;
        public Sprite flag;
    }

    [SerializeField] int buildRevision;
    [SerializeField] List<Entry> countries = new List<Entry>();
    [SerializeField] Sprite worldCupTrophy;

    static CountryCatalog instance;
    Dictionary<string, Entry> byCountry;

    public int BuildRevision => buildRevision;
    public IReadOnlyList<Entry> Countries => countries;
    public Sprite WorldCupTrophy => worldCupTrophy;

    public static CountryCatalog Instance
    {
        get
        {
            if (instance == null) instance = Resources.Load<CountryCatalog>("CountryCatalog");
            return instance;
        }
    }

    public Entry Get(string country)
    {
        EnsureLookup();
        return !string.IsNullOrEmpty(country) && byCountry.TryGetValue(country, out Entry entry)
            ? entry : null;
    }

    public Sprite FlagFor(string country) => Get(country)?.flag;
    public int WinRateFor(string country) => Get(country)?.winRate ?? 50;

    void EnsureLookup()
    {
        if (byCountry != null) return;
        byCountry = new Dictionary<string, Entry>(StringComparer.Ordinal);
        foreach (Entry entry in countries)
            if (entry != null && !string.IsNullOrEmpty(entry.country))
                byCountry[entry.country] = entry;
    }
}
