using System;
using System.Collections.Generic;
using UnityEngine;

// Generated by CrestTemplateBuilder. Each mask packs primary/secondary/tertiary/fixed pixels into
// RGBA, allowing one UI Image and one material pass per crest.
[CreateAssetMenu(fileName = "CrestTemplateCatalog", menuName = "Water Polo/Crest Template Catalog")]
public class CrestTemplateCatalog : ScriptableObject
{
    [Serializable]
    public class Entry
    {
        public string id;
        public bool valid;
        public Sprite mask;
        public float primaryCoverage;
        public float secondaryCoverage;
        public float tertiaryCoverage;
        public string qcNote;
    }

    [SerializeField] private int buildRevision;
    [SerializeField] private string sourceSignature;
    [SerializeField] private Material tintMaterial;
    [SerializeField] private List<Entry> templates = new List<Entry>();

    static CrestTemplateCatalog instance;

    public int BuildRevision => buildRevision;
    public string SourceSignature => sourceSignature;
    public int Count => templates != null ? templates.Count : 0;
    public Material TintMaterial => tintMaterial;

    public static CrestTemplateCatalog Instance
    {
        get
        {
            if (instance == null) instance = Resources.Load<CrestTemplateCatalog>("CrestTemplateCatalog");
            return instance;
        }
    }

    public Entry Get(int index)
    {
        if (templates == null || index < 0 || index >= templates.Count) return null;
        return templates[index];
    }

    public int FirstValidIndex()
    {
        if (templates == null) return 0;
        for (int i = 0; i < templates.Count; i++)
            if (templates[i] != null && templates[i].valid && templates[i].mask != null) return i;
        return 0;
    }

    public int NextValidIndex(int current, int direction)
    {
        if (Count == 0) return 0;
        direction = direction < 0 ? -1 : 1;
        int index = Mathf.Clamp(current, 0, Count - 1);
        for (int checkedCount = 0; checkedCount < Count; checkedCount++)
        {
            index = (index + direction + Count) % Count;
            Entry entry = Get(index);
            if (entry != null && entry.valid && entry.mask != null) return index;
        }
        return FirstValidIndex();
    }
}
